// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLink: typeof import('./src/components/SocialLink.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
